language: python
python: 
    - "3.6"
    - "3.9-dev"
before_install:
    - python version
    - pip install -U pip
    - pip install -U pytest
install:   
    - pip install -r requirements.txt
script:
    - pytest        


